services:
  broker:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  jaegger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686" # Jaeger UI
      - "6831:6831/udp" # Traces UDP
      - "14268:14268" # Traces HTTP
      - "4317:4317" # OTLP/gRPC
      - "4318:4318" # OTLP/HTTP

volumes:
  rabbitmq_data: