services:
  invoices-pg:
    image: bitnami/postgresql:latest
    posts:
      - '5483:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=invoices
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
