services:
  pg:
    image: bitnami/postgresql:latest
    posts:
      - '5482:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
